version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - SQLALCHEMY_STRING=postgresql://duytien:okbaby@db:5432/task_management_db
    depends_on:
      - db
    volumes:
      - ./app:/fastapi-app/app

  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: duytien
      POSTGRES_PASSWORD: okbaby
      POSTGRES_DB: task_management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
